name: gospl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - meson-python>=0.15.0
  - setuptools>=61.0
  - pkg-config
  - build
  - numpy
  - petsc4py
  - pip
  - scipy
  - numpy-indexed
  - pandas
  - h5py
  - meshio
  - vtk
  - pre-commit
  - ruamel.yaml
  - mpi4py
  - cython
  - compilers
  - meshplex
  - gflex
  - netcdf4
  - xarray
  - rioxarray
  - uxarray
  - pyinterp
  - jigsawpy
  - stripy
  - xesmf
  - mpas_tools
  - pygmt
  - rasterio
  - pysheds
  - seaborn
  - pyevtk
  - basemap
  - numba
  - shapely
  - pyvista
  - pyproj 
  - triangle
  - pip:
    - git+https://github.com/Geodels/isoFlex.git
    - git+https://github.com/Geodels/gospl.git@2024.09.01
